services:
    api:
        build:
            target: development
        environment:
            ASPNETCORE_ENVIRONMENT: Development
        volumes:
            - ./api:/api
            - /api/Application/obj
            - /api/Application/bin

    cms:
        build:
            target: development
        volumes:
            - ./cms:/cms
            - /cms/node_modules
            - /cms/.strapi
            - /cms/dist

    front:
        build:
            target: development
        volumes:
            - ./front:/front
            - /front/node_modules

    test-api:
        environment:
            ASPNETCORE_ENVIRONMENT: Development


