services:
    api:
        build:
            target: development
        environment:
            ASPNETCORE_ENVIRONMENT: Development
    cms:
        build:
            target: development

    front:
        build:
            target: development


