server {
    listen 80;
    server_name admin.avelee.online;

    resolver 127.0.0.11 valid=10s;

    location / {
        set $upstream_cms cms:1337;
        proxy_pass http://$upstream_cms;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name avelee.online;

    resolver 127.0.0.11 valid=10s;

    location /api/ {
        set $upstream_api api:5201;
        proxy_pass http://$upstream_api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        set $upstream_front front:5173;
        proxy_pass http://$upstream_front/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
