FROM node:24 AS build
WORKDIR /cms
COPY package*.json .
RUN npm install
COPY . .
EXPOSE 1337

FROM build AS development
ENTRYPOINT ["npm", "run", "develop", "--", "--debug"]

FROM build AS production
RUN npm prune --omit=dev
RUN npm run build
ENTRYPOINT ["npx", "strapi", "start"]
